AnimeCore/Areas/Admin/Controllers/MovieController.cs
using System.Linq;
using System.Threading.Tasks;
using AnimeCore.Common;
using Entities.Domain;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Repositories;

namespace AnimeCore.Areas.Admin.Controllers
{
    public class MovieController : AdminController
    {
        private readonly IMovieRepository _movieRepository;
        private readonly IUnitOfWork _unitOfWork;

        public MovieController(IUnitOfWork unitOfWork, IMovieRepository movieRepository)
        {
            _unitOfWork = unitOfWork;
            _movieRepository = movieRepository;
        }

        public IActionResult Index()
        {
            var model = _movieRepository.GetAll();
            return View(model);
        }

        public IActionResult Add()
        {
            var model = new Movie();
            ViewData["SelectGenres"] = 1;
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(Movie model, int[] genres, IFormFile image, IFormFile slide)
        {
            if (image == null)
            {
                ModelState.AddModelError(string.Empty, "Image is required.");
            }

            if (ModelState.IsValid)
            {
                await UpdateFileIfExistAsync(model, image, slide);

                foreach (var genre in genres)
                {
                    model.GenreMovies.Add(new GenreMovie
                    {
                        GenreId = genre
                    });
                }

                _movieRepository.Add(model);
                await _unitOfWork.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            ViewData["SelectGenres"] = genres;
            return View(model);
        }

        public IActionResult Edit(int id)
        {
            var model = _movieRepository.FindById(id);
            if (model == null)
            {
                return NotFound();
            }
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Movie model, int[] genres, IFormFile image, IFormFile slide)
        {
            if (ModelState.IsValid)
            {
                var movie = _movieRepository.FindById(model.Id);
                if (movie == null)
                {
                    return NotFound();
                }

                await UpdateFileIfExistAsync(movie, image, slide);

                UpdateGenre(movie, genres);

                movie.Name = model.Name;
                movie.Status = model.Status;
                movie.Release = model.Release;
                movie.Description = model.Description;

                _movieRepository.Update(movie);
                await _unitOfWork.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        public IActionResult Delete(int id)
        {
            var model = _movieRepository.FindById(id);
            if (model == null)
            {
                return NotFound();
            }
            return PartialView("_DeletePartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(Movie model)
        {
            _movieRepository.Remove(model);
            await _unitOfWork.SaveChangesAsync();
            return JsonStatus.Ok;
        }

        private void UpdateGenre(Movie movie, int[] genres)
        {
            foreach (var genre in genres)
            {
                if (movie.GenreMovies.All(x => x.GenreId != genre))
                {
                    movie.GenreMovies.Add(new GenreMovie
                    {
                        GenreId = genre
                    });
                }
            }

            foreach (var gm in movie.GenreMovies.ToList())
            {
                if (genres.All(x => x != gm.GenreId))
                {
                    movie.GenreMovies.Remove(gm);
                }
            }
        }

        private async Task UpdateFileIfExistAsync(Movie movie, IFormFile image, IFormFile slide)
        {
            if (image != null)
            {
                movie.Image = await UploadAsync(image);
            }
            if (slide != null)
            {
                movie.Slide = await UploadAsync(slide);
            }
        }
    }
}

AnimeCore/Controllers/MovieController.cs
using System.Threading.Tasks;
using AnimeCore.Common;
using Entities.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Repositories;
using Services;

namespace AnimeCore.Controllers
{
    public class MovieController : Controller
    {
        private readonly AppSettings _appSettings;
        private readonly IMovieRepository _movieRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IUserService _userService;
        private readonly IVideoAdsRepository _videoAdsRepository;

        public MovieController(IOptionsSnapshot<AppSettings> appSettings,
            IMovieRepository movieRepository, IVideoAdsRepository videoAdsRepository, IUnitOfWork unitOfWork,
            IUserService userService)
        {
            _appSettings = appSettings.Value;
            _movieRepository = movieRepository;
            _videoAdsRepository = videoAdsRepository;
            _unitOfWork = unitOfWork;
            _userService = userService;
        }

        // GET: /Movie/Index
        public IActionResult Index(string searchString, string releaseYear)
        {
            ViewData[Constant.SearchString] = searchString;
            ViewData[Constant.PageSize] = _appSettings.PageSize;
            ViewData["ReleaseYear"] = releaseYear;
            return View();
        }

        // GET: /Movie/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = _movieRepository.FindById(id);
            if (model == null)
            {
                return NotFound();
            }
            ViewData["HasLike"] = false;
            if (User.Identity.IsAuthenticated)
            {
                ViewData["HasLike"] = _movieRepository.HasLike(await _userService.GetUserAsync(User), model);
            }
            return View(model);
        }

        // GET: /Movie/Watch/5
        public async Task<IActionResult> Watch(int id)
        {
            var model = _movieRepository.FindById(id);
            if (model == null)
            {
                return NotFound();
            }
            var advertisement = _videoAdsRepository.GetActiveVideos("Normal").PickRandom();
            if (_movieRepository.IsPopular(model.Id))
            {
                advertisement = _videoAdsRepository.GetActiveVideos("Popular").PickRandom();
            }
            else if (_movieRepository.IsMostLiked(model.Id))
            {
                advertisement = _videoAdsRepository.GetActiveVideos("Most Liked").PickRandom();
            }
            else if (_movieRepository.IsNewest(model.Id))
            {
                advertisement = _videoAdsRepository.GetActiveVideos("Newest").PickRandom();
            }

            model.View = model.View + 1;
            await _unitOfWork.SaveChangesAsync();

            ViewData["Advertisement"] = advertisement;
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Like(int id)
        {
            var movie = _movieRepository.FindById(id);
            if (movie == null)
            {
                return NotFound();
            }
            if (!_movieRepository.HasLike(await _userService.GetUserAsync(User), movie))
            {
                _movieRepository.Like(await _userService.GetUserAsync(User), movie);
                _unitOfWork.SaveChanges();
            }
            return RedirectToAction("Details", new {id});
        }

        [Authorize]
        public async Task<IActionResult> UnLike(int id)
        {
            var movie = _movieRepository.FindById(id);
            if (movie == null)
            {
                return NotFound();
            }
            _movieRepository.UnLike(await _userService.GetUserAsync(User), movie);
            _unitOfWork.SaveChanges();
            return RedirectToAction("Details", new {id});
        }
    }
}

AnimeCore/ViewComponents/MovieSlideViewComponent.cs
using System.Collections.Generic;
using AnimeCore.Common;
using Entities.Domain;
using Microsoft.AspNetCore.Mvc;

namespace AnimeCore.ViewComponents
{
    [ViewComponent(Name = "MovieSlide")]
    public class MovieSlideViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(IEnumerable<Movie> model, string title, int rows = 1)
        {
            ViewData[Constant.SlideTitle] = title;
            ViewData["Rows"] = rows;
            return View(model);
        }
    }
}

AnimeCore/Views/Movie/Details.cshtml
@model Movie
@inject IBannerAdsRepository BannerAdsRepository
@{
    ViewData[Constant.Title] = Model.Name + " - Details";
}

@section Slide {
    <a asp-action="Watch" asp-controller="Movie" asp-route-id="@Model.Id">
        <img src="@Model.Slide" alt="@Model.Name" class="img-responsive center-block" asp-append-version="true" style="width: 100%">
    </a>
}

@section TopAds {
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Top", BannerType.Child).PickRandom())
}

@section RightAds {
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Right 1", BannerType.Child).PickRandom())
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Right 2", BannerType.Child).PickRandom())
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Right 3", BannerType.Child).PickRandom())
}

@section BottomAds {
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Bottom", BannerType.Child).PickRandom())
}

@section Balloon {
    @await Html.PartialAsync("_RightBalloonPartial", BannerAdsRepository.GetActiveBanners("Right Balloon", BannerType.Child).PickRandom())
}

<ol class="breadcrumb">
    <li>
        <a href="/">Home</a>
    </li>
    <li class="active">
        @Model.Name
    </li>
</ol>
<div class="panel panel-info" id="panel-movie-detail">
    <div class="panel-heading">
        @Model.Name
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-9">
                <div class="col-sm-12">
                    <display name-for="GenreMovies"></display>:
                    @{
                        var i = 0;
                    }
                    @foreach (var genreMovies in Model.GenreMovies)
                    {
                        @(i++ > 0 ? ", " : "")
                        <a asp-action="Index" asp-controller="Movie" asp-route-id="@genreMovies.GenreId" title="@genreMovies.Genre.Title">
                            @genreMovies.Genre.Name
                        </a>
                    }
                </div>
                <div class="col-sm-12">
                    <display name-for="Fansub"/>:
                    @Model.Fansub
                </div>
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-4">
                            Episodes:
                            @Model.Episodes.Count / @(Model.Status == MovieStatus.Ongoing ? "??" : Model.Episodes.Count.ToString())
                        </div>
                        <div class="col-sm-4">
                            <display name-for="Release"/>:
                            @Model.Release.Month/@Model.Release.Year
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <div class="row">
                        <div class="col-sm-4">
                            <i class="fa fa-eye" style="color: #006400"></i>
                            @Model.View
                        </div>
                        <div class="col-sm-4">
                            <i class="fa fa-heart" style="color: #ff0000"></i>
                            @Model.Likes.Count
                        </div>
                    </div>
                </div>
                <div class="col-sm-12">
                    <display name-for="Description"/>:
                    <p style="font-size: 10px">
                        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;@Model.Description
                    </p>
                </div>
                <div class="col-sm-12">
                    <div class="form-group">
                        <div class="text-center">
                            <a asp-action="Watch" asp-controller="Movie" asp-route-id="@Model.Id" class="btn btn-primary">
                                <i class="fa fa-video-camera"></i>
                                Watch
                            </a>
                            <form asp-action="@((bool) ViewData["HasLike"] ? "UnLike" : "Like")" asp-controller="Movie" asp-route-id="@Model.Id" style="display: inline">
                                <button type="submit" class="btn btn-danger">
                                    @if ((bool) ViewData["HasLike"])
                                    {
                                        <i class="fa fa-heart-o"></i>
                                        <span>UnLike</span>
                                    }
                                    else
                                    {
                                        <i class="fa fa-heart"></i>
                                        <span>Like</span>
                                    }
                                </button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-12 col-sm-3">
                <img class="img-rounded img-responsive center-block" src="@Model.Image" alt="@Model.Name" asp-append-version="true"/>
            </div>
        </div>
    </div>
    <div class="panel-footer">
    </div>
</div>

<div class="fb-comments" data-href="@($"{Context.Request.Scheme}://{Context.Request.Host}{Context.Request.Path}{Context.Request.QueryString}")" data-numposts="10" data-width="100%" data-mobile="true" data-colorscheme="dark"></div>

AnimeCore/Views/Movie/Index.cshtml
@inject IGenreRepository GenreRepository
@inject IBannerAdsRepository BannerAdsRepository
@{
    ViewData[Constant.Title] = "Search";
}

@section Slide {
    @await Html.PartialAsync("_SlidePartial")
}

@section TopAds {
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Top", BannerType.Child).PickRandom())
}

@section RightAds {
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Right 1", BannerType.Child).PickRandom())
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Right 2", BannerType.Child).PickRandom())
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Right 3", BannerType.Child).PickRandom())
}

@section BottomAds {
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Bottom", BannerType.Child).PickRandom())
}

@section Balloon {
    @await Html.PartialAsync("_RightBalloonPartial", BannerAdsRepository.GetActiveBanners("Right Balloon", BannerType.Child).PickRandom())
}

<div ng-app="app" ng-controller="movie-controller">
    <div class="panel panel-primary">
        <div class="panel-heading">
            Filter
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-6 col-sm-3">
                    <div class="form-group">
                        <div align="center">Genres:</div>
                        <select class="form-control" data-live-search="true" ng-model="genreId">
                            <option value="">All</option>
                            @foreach (var genre in GenreRepository.ToList())
                            {
                                <option value="@genre.Id">@genre.Name</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3">
                    <div class="form-group">
                        <div align="center">Release:</div>
                        <select class="form-control" ng-model="release">
                            <option value="">All</option>
                            @for (var i = DateTime.Now.Year; i >= 2010; i--)
                            {
                                <option value="@i">@i</option>
                            }
                        </select>
                    </div>
                </div>
                <div class="col-xs-6 col-sm-3">
                    <div class="form-group">
                        <div align="center">Status:</div>
                        <select class="form-control" ng-model="status">
                            <option value="">All</option>
                            <option value="1">Completed</option>
                            <option value="0">Ongoing</option>
                        </select>
                    </div>

                </div>
                <div class="col-xs-6 col-sm-3">
                    <div class="form-group">
                        <div align="center">Sort by:</div>
                        <select class="form-control" ng-model="propertyName">
                            <option value="name">A-Z</option>
                            <option value="-name">Z-A</option>
                            <option value="-view">View</option>
                            <option value="-likes.length">Like</option>
                        </select>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="panel panel-info" id="panel-movie-list">
        <div class="panel-heading">
            Result
        </div>
        <div class="panel-body">
            <div class="row">
                <div class="col-xs-6 col-sm-4 col-md-3" dir-paginate="movie in movies | orderBy:propertyName:reverse | filter:{ status:status, release:release, genreMovies: {genreId:genreId} } | itemsPerPage:@ViewData[Constant.PageSize]">
                    <a href="@Url.Action("Details")/{{ movie.id }}">
                        <div class="movie-content" title="{{ movie.name }}">
                            <div class="movie-info">
                                <span class="pull-left" style="margin-bottom: 5px; margin-left: 5px;">
                                    <label class="label label-primary">
                                        {{ (movie.episodes).length }}
                                        <span ng-if="movie.status == 0">/ ??</span>
                                        <span ng-if="movie.status == 1">/ {{ movie.episodes.length }}</span>
                                        Ep
                                    </label>
                                </span>
                                <span class="pull-right" style="margin-right: 5px;">
                                    <label class="label label-danger">
                                        <i class="fa fa-heart"></i> {{ movie.likes.length }}
                                    </label>
                                </span>
                                <span class="movie-name col-xs-12">
                                    <label style="margin: 2px">
                                        {{ movie.name }}
                                    </label>
                                </span>
                            </div>
                            <span class="movie-release">
                                <label class="label label-warning">
                                    {{ movie.release | date:"MM/yyyy" }}
                                </label>
                            </span>
                            <span class="movie-view">
                                <label class="label label-success">
                                    <i class="fa fa-eye"></i>
                                    {{ movie.view }}
                                </label>
                            </span>
                            <img class="movie-img img-responsive" src="{{ movie.image }}" alt="{{ movie.name }}" asp-append-version="true">
                        </div>
                    </a>
                </div>
            </div>
        </div>
        <div class="panel-footer" align="center">
            <dir-pagination-controls max-size="10" direction-links="true" boundary-links="true"></dir-pagination-controls>
        </div>
    </div>
</div>

@section Scripts {
    <script src="~/lib/angular/angular.js"></script>
    <script src="~/lib/angularUtils-pagination/dirPagination.js"></script>

    <script>
        (function() {
            "use strict";
            var app = angular.module("app", ["angularUtils.directives.dirPagination"]);
            app.controller("movie-controller", controller);
            app.filter("status",
                function() {
                    return function(data) {
                        if (data === 1) {
                            return "Completed";
                        }
                        return "Ongoing";
                    };
                });

            controller.$inject = ["$scope", "$http"];

            function controller($scope, $http) {
                $http.get("@Url.Action("GetMovies", "MovieApi", new {searchString = ViewData[Constant.SearchString]})")
                    .then(function(response) {
                        $scope.movies = response.data;
                        $scope.$watch('$viewContentLoaded',
                            function() {
                                $scope.propertyName = "name";
                                $scope.reverse = false;
                                $scope.status = "";
                                $scope.release = "@ViewData["ReleaseYear"]";
                                $scope.genreId = "@Url.ActionContext.RouteData.Values["id"]";
                            });
                    });
                activate();

                function activate() {}
            }
        })();
    </script>
}

AnimeCore/Views/Movie/Watch.cshtml
@model Movie
@inject IMovieRepository MovieRepository
@inject IBannerAdsRepository BannerAdsRepository
@inject IEpisodeRepository EpisodeRepository

@{
    ViewData[Constant.Title] = Model.Name + " - Watch";
    dynamic advertisement = ViewData["Advertisement"];
}

@section Slide {
    <div class="row">
        <div class="col-xs-12">
            <div id="player" class="embed-responsive embed-responsive-16by9">
                <!-- ads-area -->
                <div id="ads-area">
                    <a href="#" class="video-ads-link">
                        <video class="embed-responsive-item" autoplay=""></video>
                    </a>
                    <div id="ads-skip" class="col-xs-12">
                        <div class="pull-right">
                            <div class="text-center" style="font-size: 20px">
                                <label class="label label-default">
                                    <a href="#" style="color: white">
                                        Skip Ad in @advertisement.SkipIn
                                    </a>
                                </label>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.ads-area -->
            </div>
        </div>
    </div>

}

@section TopAds {
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Top", BannerType.Child).PickRandom())
}

@section RightAds {
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Right 1", BannerType.Child).PickRandom())
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Right 2", BannerType.Child).PickRandom())
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Right 3", BannerType.Child).PickRandom())
}

@section BottomAds {
    @await Html.PartialAsync("_BannerPartial", BannerAdsRepository.GetActiveBanners("Bottom", BannerType.Child).PickRandom())
}

@section Balloon {
    @await Html.PartialAsync("_RightBalloonPartial", BannerAdsRepository.GetActiveBanners("Right Balloon", BannerType.Child).PickRandom())
}

<div class="panel panel-info" id="panel-movie-detail">
    <div class="panel-heading">
        Episode list
    </div>
    <div class="panel-body">
        <div class="row">
            <div class="col-sm-12">
                @foreach (var item in EpisodeRepository.OrderByName(Model.Episodes))
                {
                    <button class="btn btn-primary btn-episode" data-src="@item.Source" style="margin-bottom: 10px">@(item.Name.Length == 1 ? "0" : "")@item.Name</button>
                }
            </div>
        </div>
    </div>
</div>

<vc:movie-slide model="@MovieRepository.GetAll().PickRandom(36)" title="Recommend" rows="3"></vc:movie-slide>

@section Scripts {
    <script>
        $(document).ready(function() {
            var ads = $("#ads-area");
            
            @if (advertisement != null)
            {
                <text>
                    var adsLink = ads.find("a");
                    var adsVideo = ads.find("video");
                    adsLink.attr("href", "@advertisement.Url");
                    adsLink.attr("title", "@advertisement.Title");
                    adsLink.attr("target", "_blank");
                    adsVideo.attr("src", "@advertisement.Source");

                    adsVideo.on("ended",
                        function() {
                            skipAds();
                        });

                    var counter = @advertisement.SkipIn;
                    var adsSkipLink = $("#ads-skip").find("a");
                    var interval = setInterval(function() {
                            counter--;
                            adsSkipLink.html("Skip Ad in " + counter);
                            if (counter <= 0) {
                                adsSkipLink.html('Skip Ad <i class="fa fa-forward"></i>');
                                adsSkipLink.click(function(e) {
                                    e.preventDefault();
                                    skipAds();
                                });
                                $.ajax({
                                    type: "POST",
                                    url: "@Url.Action("VideoOnSkip", "Advertisement")",
                                    data: {
                                        id: "@advertisement.Id"
                                    },
                                    success: function(data) {
                                        console.log(data);
                                    },
                                    error: function() {
                                        console.log("error");
                                    }
                                });
                                clearInterval(interval);
                            }
                        },
                        1000);

                    $(".video-ads-link").click(function() {
                        $.ajax({
                            type: "POST",
                            url: "@Url.Action("VideoOnClick", "Advertisement")",
                            data: {
                                id: "@advertisement.Id"
                            },
                            success: function(data) {
                                console.log(data);
                            },
                            error: function() {
                                console.log("error");
                            }
                        });
                    });
                </text>
            }
            else
            {
                <text>skipAds();</text>
            }
           
            function skipAds() {
                ads.remove();
                $("#player")
                    .append('<iframe id="movie" class="embed-responsive-item" src="" allowfullscreen></iframe>');
                $('.btn-episode:first').trigger('click');
            }

            $('.btn-episode').on('click',
                function() {
                    $('#movie').attr("src", $(this).data("src"));
                    $('.btn-episode').removeClass("active");
                    $(this).addClass("active");
                });
        });
    </script>
}