AnimeCore/Areas/Admin/Controllers/ClaimController.cs
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using AnimeCore.Common;
using Microsoft.AspNetCore.Mvc;
using Models.ClaimViewModels;
using Services;

namespace AnimeCore.Areas.Admin.Controllers
{
    public class ClaimController : AdminIdentityController
    {
        private readonly IRoleService _roleService;

        public ClaimController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        public async Task<IActionResult> Index(string roleId)
        {
            var role = await _roleService.FindByIdAsync(roleId);
            if (role == null)
            {
                return NotFound();
            }
            ViewData["Role"] = role;

            var model = Constant.Claims.Select(x => new ClaimViewModel
            {
                Controller = x.Type,
                Action = x.Value,
                IsEnabled = false
            }).ToList();

            var claims = await _roleService.GetClaimsAsync(role);

            foreach (var item in model)
            {
                if (claims.Any(roleClaim =>
                    roleClaim.Type == item.Controller && roleClaim.Value == item.Action))
                {
                    item.IsEnabled = true;
                }
            }

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Index(string controllerName, string actionName, string roleId,
            string operation)
        {
            var role = await _roleService.FindByIdAsync(roleId);
            if (role == null)
            {
                return JsonStatus.Error;
            }
            dynamic result;
            switch (operation)
            {
                case "Enable":
                    result = await _roleService.AddClaimAsync(role, new Claim(controllerName, actionName));
                    break;
                case "Disable":
                    result = await _roleService.RemoveClaimAsync(role, new Claim(controllerName, actionName));
                    break;
                default:
                    return JsonStatus.Error;
            }
            if (result.Succeeded)
            {
                return JsonStatus.Ok;
            }
            AddErrors(result);
            return JsonStatus.Error;
        }
    }
}

AnimeCore/Areas/Admin/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnimeCore.Common;
using Entities.Domain;
using Microsoft.AspNetCore.Mvc;
using Models.UserViewModels;
using Services;

namespace AnimeCore.Areas.Admin.Controllers
{
    public class UserController : AdminIdentityController
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var model = new List<UserListViewModel>();
            foreach (var item in _userService.ToList())
            {
                model.Add(new UserListViewModel
                {
                    Id = item.Id,
                    Email = item.Email,
                    UserName = item.UserName,
                    EmailConfirmed = item.EmailConfirmed,
                    RoleName = (await _userService.GetRolesAsync(item)).FirstOrDefault()
                });
            }
            return View(model.AsEnumerable());
        }

        public IActionResult Add()
        {
            return PartialView("_AddPartial");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User
                {
                    UserName = model.UserName,
                    Email = model.Email
                };
                var result = await _userService.CreateAsync(user, model.Password, model.RoleName);
                if (result.Succeeded)
                {
                    return JsonStatus.Ok;
                }
                AddErrors(result);
            }
            return PartialView("_AddPartial", model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userService.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                RoleName = (await _userService.GetRolesAsync(user)).FirstOrDefault()
            };
            return PartialView("_EditPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userService.FindByIdAsync(model.Id);
                if (user == null)
                {
                    return NotFound();
                }
                user.Email = model.Email;
                user.UserName = model.UserName;
                var result = await _userService.UpdateAsync(user, model.RoleName);
                if (result.Succeeded)
                {
                    return JsonStatus.Ok;
                }
                AddErrors(result);
            }
            return PartialView("_EditPartial", model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userService.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new UserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                RoleName = (await _userService.GetRolesAsync(user)).FirstOrDefault()
            };
            return PartialView("_DeletePartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(UserViewModel model)
        {
            var user = await _userService.FindByIdAsync(model.Id);
            if (user == null)
            {
                return NotFound();
            }
            var result = await _userService.DeleteAsync(user);
            if (result.Succeeded)
            {
                return JsonStatus.Ok;
            }
            AddErrors(result);
            return PartialView("_DeletePartial", model);
        }
    }
}

AnimeCore/Areas/Admin/Views/User/Add.cshtml
@using Models.ModalViewModels
@model Models.UserViewModels.AddUserViewModel

<form asp-action="Add" asp-controller="User" method="post">
    @await Html.PartialAsync("Modal/_HeaderPartial", new ModalHeader {Heading = "Add User"})
    <div class="modal-body form-horizontal">
        <div class="row">
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="UserName" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="UserName" class="form-control"/>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="Email" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="Email" class="form-control"/>
                    </div>
                </div>
            </div>
            <div class="col-sm-6">
                <div class="form-group">
                    <label asp-for="Password" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="Password" class="form-control"/>
                    </div>
                </div>
                <div class="form-group">
                    <label asp-for="ConfirmPassword" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="ConfirmPassword" class="form-control"/>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @await Html.PartialAsync("Modal/_FooterPartial", new ModalFooter())
</form>

AnimeCore/Areas/Admin/Views/User/Index.cshtml
@using Models.ModalViewModels
@inject IRoleService RoleService
@model IEnumerable<Models.UserViewModels.UserListViewModel>
@{
    ViewData[Constant.Title] = "User List";
}

@await Html.PartialAsync("Modal/_ModalPartial", new Modal {Id = "user-action-modal", ModalSize = ModalSize.Medium})

<div class="panel panel-info">
    <div class="panel-heading">
        <h4 class="panel-title">
            @ViewData[Constant.Title]
        </h4>
    </div>
    <div class="panel-body">
        <div class="btn-group">
            <a asp-action="Add" class="btn btn-primary @(User.HasClaim("User", "Add") ? "" : "disabled")" data-toggle="modal" data-target="#user-action-modal">
                <i class="fa fa-plus"></i> Add User
            </a>
        </div>
        <div class="top-buffer"></div>
        <div class="table-responsive">
            <table class="table table-striped table-bordered table-hover" id="dataTables">
                <thead>
                <tr>
                    <th>
                        No
                    </th>
                    <th>
                        <display name-for="@Model.First().UserName"></display>
                    </th>
                    <th>
                        <display name-for="@Model.First().Email"></display>
                    </th>
                    <th>
                        <display name-for="@Model.First().RoleName"></display>
                    </th>
                    <th style="width: 20px;">#</th>
                    <th style="width: 20px;">#</th>
                </tr>
                </thead>
                <tbody>
                @{
                    var i = 1;
                }
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@(i++)</td>
                        <td>@item.UserName</td>
                        <td>@item.Email</td>
                        <td>
                            @if (!string.IsNullOrEmpty(item.RoleName))
                            {
                                <a asp-action="Index" asp-controller="Claim" asp-route-roleId="@((await RoleService.FindByNameAsync(item.RoleName)).Id)">
                                    @item.RoleName
                                </a>
                            }
                        </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-info @(User.HasClaim("User", "Edit") ? "" : "disabled")" data-toggle="modal" data-target="#user-action-modal">
                                <i class="fa fa-pencil"></i> Edit
                            </a>
                        </td>
                        <td>
                            <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger @(User.HasClaim("User", "Delete") && item.UserName != User.Identity.Name ? "" : "disabled")" data-toggle="modal" data-target="#user-action-modal">
                                <i class="fa fa-trash"></i> Delete
                            </a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Scripts {
    @await Html.PartialAsync("_ValidationScriptsPartial")
    <script src="~/assets/admin/js/modal-remote-setup.js" asp-append-version="true"></script>
    <script src="~/assets/admin/js/modal-form.js" asp-append-version="true"></script>
}

AnimeCore/Areas/Admin/Views/User/_AddPartial.cshtml
@inject IRoleService RoleService
@using Models.ModalViewModels
@model Models.UserViewModels.AddUserViewModel

<form asp-action="Add" asp-controller="User" method="post" class="modal-form">
    @await Html.PartialAsync("Modal/_HeaderPartial", new ModalHeader {Heading = "Add User"})
    <div class="modal-body form-horizontal">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="alert alert-danger col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 text-center"></div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="UserName" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="UserName" class="form-control"/>
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="Email" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="Email" class="form-control"/>
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="RoleName" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <select asp-for="RoleName" asp-items="@(new SelectList(RoleService.ToList(), "Name", "Name"))" class="selectpicker show-tick form-control"></select>
                        <span asp-validation-for="RoleName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="Password" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="Password" class="form-control"/>
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="ConfirmPassword" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="ConfirmPassword" class="form-control"/>
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @await Html.PartialAsync("Modal/_FooterPartial", new ModalFooter {SubmitButtonText = "Add", SubmitButtonClass = "btn-primary"})
</form>

<script>
    $('.selectpicker').selectpicker();
    $.validator.unobtrusive.parse(".modal-form");
</script>

AnimeCore/Areas/Admin/Views/User/_DeletePartial.cshtml
@using Models.ModalViewModels
@model Models.UserViewModels.UserViewModel

<form asp-action="Delete" asp-controller="User" method="post" class="modal-form">
    @await Html.PartialAsync("Modal/_HeaderPartial", new ModalHeader {Heading = "Delete User"})
    <div class="modal-body form-horizontal">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="alert alert-danger col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 text-center"></div>
            <div class="text-center col-sm-12">
                <h4>Are you want to delete this user?</h4>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="UserName" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="UserName" class="form-control" readonly=""/>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="Email" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="Email" class="form-control" readonly=""/>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="RoleName" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="RoleName" class="form-control" readonly=""/>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @await Html.PartialAsync("Modal/_FooterPartial", new ModalFooter {SubmitButtonText = "Delete", SubmitButtonClass = "btn-danger"})
</form>

AnimeCore/Areas/Admin/Views/User/_EditPartial.cshtml
@inject IRoleService RoleService
@using Models.ModalViewModels
@model Models.UserViewModels.EditUserViewModel

<form asp-action="Edit" asp-controller="User" method="post" class="modal-form">
    @await Html.PartialAsync("Modal/_HeaderPartial", new ModalHeader {Heading = "Edit User"})
    <div class="modal-body form-horizontal">
        <div class="row">
            <div asp-validation-summary="ModelOnly" class="alert alert-danger col-xs-offset-1 col-xs-10 col-sm-offset-2 col-sm-8 text-center"></div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="UserName" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="UserName" class="form-control"/>
                        <span asp-validation-for="UserName" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="Email" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <input asp-for="Email" class="form-control"/>
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                </div>
            </div>
            <div class="col-sm-12">
                <div class="form-group">
                    <label asp-for="RoleName" class="col-sm-3 control-label"></label>
                    <div class="col-sm-9">
                        <select asp-for="RoleName" asp-items="@(new SelectList(RoleService.ToList(), "Name", "Name"))" class="selectpicker form-control"></select>
                        <span asp-validation-for="RoleName" class="text-danger"></span>
                    </div>
                </div>
            </div>
        </div>
    </div>
    @await Html.PartialAsync("Modal/_FooterPartial", new ModalFooter {SubmitButtonText = "Edit", SubmitButtonClass = "btn-info"})
</form>

<script>
    $('.selectpicker').selectpicker();
    $.validator.unobtrusive.parse(".modal-form");
</script>