AnimeCore/Areas/Admin/Controllers/GenreController.cs
using System.Threading.Tasks;
using Entities.Domain;
using Microsoft.AspNetCore.Mvc;
using Repositories;

namespace AnimeCore.Areas.Admin.Controllers
{
    public class GenreController : DefaultController<Genre, IGenreRepository>
    {
        public GenreController(IUnitOfWork unitOfWork, IGenreRepository repository) : base(unitOfWork, repository)
        {
        }

        protected override string AddPartialViewName { get; set; } = "_AddEditPartial";
        protected override string EditPartialViewName { get; set; } = "_AddEditPartial";

        public override IActionResult Index()
        {
            return base.Index();
        }

        public override IActionResult Add()
        {
            ViewData["Action"] = "Add";
            return base.Add();
        }

        public override Task<IActionResult> Add(Genre model)
        {
            ViewData["Action"] = "Add";
            return base.Add(model);
        }

        public override IActionResult Edit(int id)
        {
            ViewData["Action"] = "Edit";
            return base.Edit(id);
        }

        public override Task<IActionResult> Edit(Genre model)
        {
            ViewData["Action"] = "Edit";
            return base.Edit(model);
        }

        public override IActionResult Delete(int id)
        {
            return base.Delete(id);
        }

        public override Task<IActionResult> Delete(Genre model)
        {
            return base.Delete(model);
        }
    }
}

AnimeCore/Areas/Admin/Controllers/RoleController.cs
using System.Linq;
using System.Threading.Tasks;
using AnimeCore.Common;
using Entities.Domain;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Models.RoleViewModels;
using Services;

namespace AnimeCore.Areas.Admin.Controllers
{
    public class RoleController : AdminIdentityController
    {
        private readonly IRoleService _roleService;

        public RoleController(IRoleService roleService)
        {
            _roleService = roleService;
        }

        public IActionResult Index()
        {
            var model = _roleService.ToList().Select(x => new RoleListViewModel
            {
                Id = x.Id,
                Name = x.Name,
                Description = x.Description,
                NumberOfUsers = x.Users.Count
            });
            return View(model);
        }

        public async Task<IActionResult> AddEdit(string id)
        {
            var model = new RoleViewModel();
            var role = await _roleService.FindByIdAsync(id);
            if (role != null)
            {
                model.Id = role.Id;
                model.Name = role.Name;
                model.Description = role.Description;
            }
            return PartialView("_AddEditPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddEdit(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = await _roleService.FindByIdAsync(model.Id);
                IdentityResult result;
                if (role != null)
                {
                    role.Name = model.Name;
                    role.Description = model.Description;
                    result = await _roleService.UpdateAsync(role);
                }
                else
                {
                    role = new Role
                    {
                        Name = model.Name,
                        Description = model.Description
                    };
                    result = await _roleService.CreateAsync(role);
                }
                if (result.Succeeded)
                {
                    return JsonStatus.Ok;
                }
                AddErrors(result);
            }
            return PartialView("_AddEditPartial", model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var role = await _roleService.FindByIdAsync(id);
            if (role == null)
            {
                return NotFound();
            }
            var model = new RoleViewModel
            {
                Id = role.Id,
                Name = role.Name,
                Description = role.Description
            };
            return PartialView("_DeletePartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(RoleViewModel model)
        {
            var role = await _roleService.FindByIdAsync(model.Id);
            if (role == null)
            {
                return NotFound();
            }
            var result = await _roleService.DeleteAsync(role);
            if (result.Succeeded)
            {
                return JsonStatus.Ok;
            }
            AddErrors(result);
            return PartialView("_DeletePartial", model);
        }
    }
}

AnimeCore/Areas/Admin/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AnimeCore.Common;
using Entities.Domain;
using Microsoft.AspNetCore.Mvc;
using Models.UserViewModels;
using Services;

namespace AnimeCore.Areas.Admin.Controllers
{
    public class UserController : AdminIdentityController
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }

        public async Task<IActionResult> Index()
        {
            var model = new List<UserListViewModel>();
            foreach (var item in _userService.ToList())
            {
                model.Add(new UserListViewModel
                {
                    Id = item.Id,
                    Email = item.Email,
                    UserName = item.UserName,
                    EmailConfirmed = item.EmailConfirmed,
                    RoleName = (await _userService.GetRolesAsync(item)).FirstOrDefault()
                });
            }
            return View(model.AsEnumerable());
        }

        public IActionResult Add()
        {
            return PartialView("_AddPartial");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Add(AddUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = new User
                {
                    UserName = model.UserName,
                    Email = model.Email
                };
                var result = await _userService.CreateAsync(user, model.Password, model.RoleName);
                if (result.Succeeded)
                {
                    return JsonStatus.Ok;
                }
                AddErrors(result);
            }
            return PartialView("_AddPartial", model);
        }

        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userService.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new EditUserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                RoleName = (await _userService.GetRolesAsync(user)).FirstOrDefault()
            };
            return PartialView("_EditPartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(EditUserViewModel model)
        {
            if (ModelState.IsValid)
            {
                var user = await _userService.FindByIdAsync(model.Id);
                if (user == null)
                {
                    return NotFound();
                }
                user.Email = model.Email;
                user.UserName = model.UserName;
                var result = await _userService.UpdateAsync(user, model.RoleName);
                if (result.Succeeded)
                {
                    return JsonStatus.Ok;
                }
                AddErrors(result);
            }
            return PartialView("_EditPartial", model);
        }

        public async Task<IActionResult> Delete(string id)
        {
            var user = await _userService.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            var model = new UserViewModel
            {
                Id = user.Id,
                Email = user.Email,
                UserName = user.UserName,
                RoleName = (await _userService.GetRolesAsync(user)).FirstOrDefault()
            };
            return PartialView("_DeletePartial", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(UserViewModel model)
        {
            var user = await _userService.FindByIdAsync(model.Id);
            if (user == null)
            {
                return NotFound();
            }
            var result = await _userService.DeleteAsync(user);
            if (result.Succeeded)
            {
                return JsonStatus.Ok;
            }
            AddErrors(result);
            return PartialView("_DeletePartial", model);
        }
    }
}

AnimeCore/Controllers/MovieController.cs
using System.Threading.Tasks;
using AnimeCore.Common;
using Entities.Domain;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Repositories;
using Services;

namespace AnimeCore.Controllers
{
    public class MovieController : Controller
    {
        private readonly AppSettings _appSettings;
        private readonly IMovieRepository _movieRepository;
        private readonly IUnitOfWork _unitOfWork;
        private readonly IUserService _userService;
        private readonly IVideoAdsRepository _videoAdsRepository;

        public MovieController(IOptionsSnapshot<AppSettings> appSettings,
            IMovieRepository movieRepository, IVideoAdsRepository videoAdsRepository, IUnitOfWork unitOfWork,
            IUserService userService)
        {
            _appSettings = appSettings.Value;
            _movieRepository = movieRepository;
            _videoAdsRepository = videoAdsRepository;
            _unitOfWork = unitOfWork;
            _userService = userService;
        }

        // GET: /Movie/Index
        public IActionResult Index(string searchString, string releaseYear)
        {
            ViewData[Constant.SearchString] = searchString;
            ViewData[Constant.PageSize] = _appSettings.PageSize;
            ViewData["ReleaseYear"] = releaseYear;
            return View();
        }

        // GET: /Movie/Details/5
        public async Task<IActionResult> Details(int id)
        {
            var model = _movieRepository.FindById(id);
            if (model == null)
            {
                return NotFound();
            }
            ViewData["HasLike"] = false;
            if (User.Identity.IsAuthenticated)
            {
                ViewData["HasLike"] = _movieRepository.HasLike(await _userService.GetUserAsync(User), model);
            }
            return View(model);
        }

        // GET: /Movie/Watch/5
        public async Task<IActionResult> Watch(int id)
        {
            var model = _movieRepository.FindById(id);
            if (model == null)
            {
                return NotFound();
            }
            var advertisement = _videoAdsRepository.GetActiveVideos("Normal").PickRandom();
            if (_movieRepository.IsPopular(model.Id))
            {
                advertisement = _videoAdsRepository.GetActiveVideos("Popular").PickRandom();
            }
            else if (_movieRepository.IsMostLiked(model.Id))
            {
                advertisement = _videoAdsRepository.GetActiveVideos("Most Liked").PickRandom();
            }
            else if (_movieRepository.IsNewest(model.Id))
            {
                advertisement = _videoAdsRepository.GetActiveVideos("Newest").PickRandom();
            }

            model.View = model.View + 1;
            await _unitOfWork.SaveChangesAsync();

            ViewData["Advertisement"] = advertisement;
            return View(model);
        }

        [Authorize]
        public async Task<IActionResult> Like(int id)
        {
            var movie = _movieRepository.FindById(id);
            if (movie == null)
            {
                return NotFound();
            }
            if (!_movieRepository.HasLike(await _userService.GetUserAsync(User), movie))
            {
                _movieRepository.Like(await _userService.GetUserAsync(User), movie);
                _unitOfWork.SaveChanges();
            }
            return RedirectToAction("Details", new {id});
        }

        [Authorize]
        public async Task<IActionResult> UnLike(int id)
        {
            var movie = _movieRepository.FindById(id);
            if (movie == null)
            {
                return NotFound();
            }
            _movieRepository.UnLike(await _userService.GetUserAsync(User), movie);
            _unitOfWork.SaveChanges();
            return RedirectToAction("Details", new {id});
        }
    }
}

AnimeCore/Areas/Admin/Views/Shared/_Layout.cshtml
@using Microsoft.Extensions.Options
@inject IOptions<Authentication> Authentication

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData[Constant.Title] - AnimeCore</title>

    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/lib/bootstrap/dist/css/bootstrap-theme.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/lib/font-awesome/css/font-awesome.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/lib/datatables/media/css/dataTables.bootstrap.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/lib/bootstrap-select/dist/css/bootstrap-select.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/lib/bootstrap-fileinput/css/fileinput.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/lib/bootstrap-toggle/css/bootstrap-toggle.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/assets/css/styles.css" rel="stylesheet" asp-append-version="true"/>
    <link href="~/assets/admin/css/site.css" rel="stylesheet" asp-append-version="true"/>
    <link href="http://cdn.datatables.net/plug-ins/1.10.15/integration/font-awesome/dataTables.fontAwesome.css" rel="stylesheet" asp-append-version="true"/>
</head>
<body>
<!-- navbar -->
@Html.Partial("_NavbarPartial")
<!-- /.navbar -->
<!-- body-content -->
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-2 col-md-2">
            @Html.Partial("_SidebarPartial")
        </div>
        <div class="col-sm-10 col-md-10">
            @RenderBody()
        </div>
    </div>
</div>
<!-- /.body-content -->

<script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
<script src="~/lib/moment/min/moment.min.js" asp-append-version="true"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
<script src="~/lib/datatables/media/js/jquery.dataTables.js" asp-append-version="true"></script>
<script src="~/lib/datatables/media/js/dataTables.bootstrap.js" asp-append-version="true"></script>
<script src="~/lib/bootstrap-select/dist/js/bootstrap-select.js" asp-append-version="true"></script>
<script src="~/lib/eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js" asp-append-version="true"></script>
<script src="~/lib/bootstrap-fileinput/js/fileinput.js" asp-append-version="true"></script>
<script src="~/lib/bootstrap-toggle/js/bootstrap-toggle.js" asp-append-version="true"></script>
<script src="~/assets/admin/js/site.js" asp-append-version="true"></script>
<script src="~/assets/js/script.js" asp-append-version="true"></script>

@RenderSection("Scripts", false)
</body>
</html>

AnimeCore/Areas/Admin/Views/Shared/_NavbarPartial.cshtml
<div class="navbar navbar-inverse">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar-collapse">
                <span class="sr-only"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="#" class="navbar-brand"> Administrator</a>
        </div>
        <div id="navbar-collapse" class="collapse navbar-collapse">
            @Html.Partial("_LoginPartial")
        </div>
    </div>
</div>

AnimeCore/Areas/Admin/Views/Shared/_SidebarPartial.cshtml
<div class="panel-group" id="accordion">
    <div class="panel panel-success">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="collapse-management">
                    <span class="fa fa-tasks">
                        Management
                    </span>
                </a>
            </h4>
        </div>
        <div id="collapse-management" class="panel-collapse collapse in">
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            <a asp-action="Index" asp-controller="User">
                                <i class="fa fa-user"></i>
                                <span>User</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a asp-action="Index" asp-controller="Role">
                                <i class="fa fa fa-id-card"></i>
                                <span>Role</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a asp-action="Index" asp-controller="Genre">
                                <i class="fa fa-list"></i>
                                <span>Genre</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a asp-action="Index" asp-controller="Movie">
                                <i class="fa fa-film"></i>
                                <span>Anime</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a asp-action="Slide" asp-controller="Setting">
                                <i class="fa fa-sliders"></i>
                                <span>Slide</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a asp-action="Index" asp-controller="Setting">
                                <i class="fa fa-cog"></i>
                                <span>Setting</span>
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>

    <div class="panel panel-warning">
        <div class="panel-heading">
            <h4 class="panel-title">
                <a data-toggle="collapse" data-parent="#accordion" href="collapse-advertisement">
                    <span class="fa fa-file">
                        Advertisement Management
                    </span>
                </a>
            </h4>
        </div>
        <div id="collapse-advertisement" class="panel-collapse collapse in">
            <div class="panel-body">
                <table class="table">
                    <tr>
                        <td>
                            <a asp-action="Index" asp-controller="Customer">
                                <i class="fa fa-group"></i>
                                <span>Customer</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a asp-action="Index" asp-controller="VideoAds">
                                <i class="fa fa-file-video-o"></i>
                                <span>Video</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a asp-action="Index" asp-controller="BannerAds">
                                <i class="fa fa-image"></i>
                                <span>Banner</span>
                            </a>
                        </td>
                    </tr>
                    <tr>
                        <td>
                            <a asp-action="Index" asp-controller="AdsLocation">
                                <i class="fa fa-list-alt"></i>
                                <span>Location</span>
                            </a>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
</div>